server:
   port: 9898

# servicio b
#http://localhost:9898/api/v1/students
zuul:
  routes:
    products:
      path: /api/v1/**
      url: https://localhost:9090/
      strip-prefix: false
#http://localhost:9898/api/version
    feign:
      path: /api/**
      url: http://localhost:8899/
      strip-prefix: false


  ssl-hostname-validation-enabled: false
 
eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    
    fetch-registry: true
    
    service-url:
     defaultzone: http://localhost:8761/eureka/
     
management:
  endpoint:
    routes:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: "*"     
